### ISSUE TITLE
TypeError parsing specific query

### ISSUE THREAD

**Issue by KidsKilla** [medialize/URI.js#238]
This one fails:
`new URI('?x&x').query(true)`

**Comment by rodneyrehm** [comment]
It fails in which way? Running your demo I get the expected result. What did you assume would happen?

```js
var data = URI('?x&x').query(true);
console.log(data);
// { "x": [null, null] }
```

**Comment by KidsKilla** [comment]
```bash
$ node
> var URI = require('URIjs');
undefined
> new URI('?x&x').query(true);
TypeError: Cannot read property 'push' of null
    at Function.URI.parseQuery (/Users/grishaev/visbookmarks-fx/backend/node_modules/URIjs/src/URI.js:613:20)
    at URI.p.query (/Users/grishaev/visbookmarks-fx/backend/node_modules/URIjs/src/URI.js:1638:18)
    at repl:1:17
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
> URI.version
'1.15.1'
```

**Comment by rodneyrehm** [comment]
Version 1.15.1 may be the problem. The current version is 1.16.0 - and it does not show your problem (not even in Node)

**Comment by KidsKilla** [comment]
Thanks!
